$cursorTheme = Bibata-Modern-Classic

env = LIBVA_DRIVER_NAME, nvidia
env = __GLX_VENDOR_LIBRARY_NAME, nvidia
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = GBM_BACKEND,nvidia-drm
env = MOZ_WEBRENDER=1
env = MOZ_ENABLE_WAYLAND=1
