### Monitors ###
monitor = HDMI-A-1, 1920x1080@165, 0x360, 1 # Primary
monitor = DP-3, 2560x1440@165, 1920x0, 1

### Workspaces ###
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-3
workspace = 3, monitor:HDMI-A-1, default:true
workspace = 4-10, monitor:HDMI-A-1

### Mouse ###
input {
    sensitivity = 0.0000
    force_no_accel=true
    accel_profile = flat
    kb_layout = eu, es # eu => eurkey
    kb_options = grp:alt_shift_toggle
}
# No anims!!
animation = workspaces, 0, 1, specialWorkSwitch

# Binds
unbind = Super, C
bind = Super, Return, exec, $terminal
bind = Super, C, killactive,

# Move window to workspace (Super+Shift+X)
bind = Super+Shift, 1, exec, $wsaction movetoworkspace 1
bind = Super+Shift, 2, exec, $wsaction movetoworkspace 2
bind = Super+Shift, 3, exec, $wsaction movetoworkspace 3
bind = Super+Shift, 4, exec, $wsaction movetoworkspace 4
bind = Super+Shift, 5, exec, $wsaction movetoworkspace 5
bind = Super+Shift, 6, exec, $wsaction movetoworkspace 6
bind = Super+Shift, 7, exec, $wsaction movetoworkspace 7
bind = Super+Shift, 8, exec, $wsaction movetoworkspace 8
bind = Super+Shift, 9, exec, $wsaction movetoworkspace 9
bind = Super+Shift, 0, exec, $wsaction movetoworkspace 10

### Misc ###
general {
    border_size = 2
}
misc {
    vrr = 1
}
